#!/bin/bash
# === allow sunlight client
xhost +

xrdb -load $E/wal/colors.Xresources
xrdb -merge $C/x11/xresources
/etc/X11/xinit/xinitrc.d/50-systemd-user.sh
fcitx5 >/dev/null 2>&1 &
# (
#   sleep 3
#   fcitx-status
# ) 2>&1 &
#sogou-qimpanel >/dev/null 2>&1&
flameshot >/dev/null 2>&1 &
dunst >/dev/null 2>&1 &
nm-applet >/dev/null 2>&1 &
urxvtd -q -o -f
xrandr --output DP-0 --mode 2560x1440 --rate 170
xrandr --auto
/usr/bin/systemd-run --scope --user tmux new -s0 -ns -d 2>&1 &
# exec xmonad
# exec dwm
#exec awesome
# exec dbus-launch --exit-with-session i3
(sleep 5; mks) 2>&1 &
exec i3
# sxhkd &

sxhkd -c $C/sxhkd/sxhkdrc_bspwm &

exec dbus-launch --exit-with-session bspwm
